refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d} [{l:>5}] {m}{n}"
  file:
    kind: file
    path: "logs/emulator.log"
    encoder:
      pattern: "{d} [{l:>5}] {m}{n}"
root:
  level: trace
  appenders:
    - stdout
loggers:
  file:
    level: trace
    appenders:
      - file
